# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-10 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_pyas2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboundfiles',
            old_name='description',
            new_name='partner',
        ),
    ]
