# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-10 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_pyas2', '0003_inboundfiles_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundfiles',
            name='file',
            field=models.FileField(upload_to=b'uploads/'),
        ),
    ]
