# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-10 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_pyas2', '0004_auto_20190710_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundfiles',
            name='partner',
        ),
        migrations.AddField(
            model_name='inboundfiles',
            name='receiver',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inboundfiles',
            name='sender',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
