# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-10 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_pyas2', '0006_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyas2.Partner'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='url',
            field=models.CharField(max_length=255, verbose_name='QU4RTET URL'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Username'),
        ),
    ]
