# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-11 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartet_pyas2', '0007_auto_20190710_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRecieved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='Id of a Message Recieved', max_length=255, verbose_name='Message Id')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
            ],
        ),
    ]
