# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-09-18 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='subject',
            field=models.CharField(default='EDI Message sent using AS2', max_length=255),
        ),
    ]
