# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-10 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as2', '0002_auto_20190710_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundfiles',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
