# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-10-28 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as2', '0002_auto_20190918_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuartetFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'uploads/')),
                ('organization', models.CharField(max_length=255, null=True)),
                ('partner', models.CharField(max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='inboundfiles',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='inboundfiles',
            name='sender',
        ),
    ]
