# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-10-28 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('as2', '0003_auto_20191028_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InboundFiles',
        ),
    ]
