# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-10-28 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as2', '0004_delete_inboundfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='content_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='payload',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
