# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-10-28 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as2', '0005_auto_20191028_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
