# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-10 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyas2', '0021_auto_20190329_2014'),
        ('as2', '0005_auto_20190710_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Route', max_length=255, verbose_name='Name')),
                ('url', models.CharField(help_text='URL of the Route. When a file is received from a Trading Partner over AS2, that file will be forwarded to this QU4RTET Server. This should be the full url. e.g. https://somewhere.qu4rtet.io/capture/quartet-capture/?rule=EPCIS', max_length=255, verbose_name='QU4RTET URL')),
                ('username', models.CharField(help_text='Username required to access QU4RTET Server.', max_length=255, verbose_name='Username')),
                ('password', models.CharField(help_text='Password required to access QU4RTET Server.', max_length=255, verbose_name='Password')),
                ('partner', models.ForeignKey(help_text='When a message is received in the AS2 Gateway, the partner is used to match up the inbound message with a QU4RTET Server', on_delete=django.db.models.deletion.CASCADE, to='pyas2.Partner')),
            ],
        ),
    ]
