# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-12-18 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as2', '0006_auto_20191028_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='as2_to_name',
            field=models.CharField(max_length=100, null=True, verbose_name='AS2 To Identifier'),
        ),
    ]
